'use client';
import {useEffect,useMemo,useState} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import {connect,EXPLORER,read,write} from '../lib/chain';

type Incident={id:string;title:string;service:string;severity:string;elapsed:string;status:string;signal:number};
type Event={time:string;kind:string;title:string;body:string;author:string};
const incidents:Incident[]=[
 {id:'INC-2471',title:'Session revocation lag',service:'IDENTITY EDGE',severity:'SEV-1',elapsed:'00:18:42',status:'CONTAIN',signal:91},
 {id:'INC-2468',title:'Write queue saturation',service:'EVENT PIPE',severity:'SEV-2',elapsed:'01:06:09',status:'OBSERVE',signal:67},
 {id:'INC-2459',title:'Token refresh drift',service:'AUTH CORE',severity:'SEV-3',elapsed:'04:27:31',status:'RECOVER',signal:38},
];
const events:Event[]=[
 {time:'21:07:12',kind:'TRIGGER',title:'Revocation latency crossed 30s',body:'P95 propagation time reached 38.4s in two identity regions. Active sessions remain valid beyond operator expectation.',author:'WATCHER-03'},
 {time:'21:09:44',kind:'REPORT',title:'Cross-region symptom confirmed',body:'EU-West and US-East share the same delayed invalidation pattern. No evidence of token forgery or signing-key exposure.',author:'M. CHEN'},
 {time:'21:13:08',kind:'ACTION',title:'Revocation writes isolated',body:'New revocation traffic routed to the priority lane. Existing queue remains intact for forensic replay.',author:'R. KLINE'},
 {time:'21:17:31',kind:'COUNCIL',title:'Containment assessment requested',body:'Situation packet sealed for independent GenLayer validator review.',author:'INCIDENT LOOM'},
];

function LoomMark(){return <svg viewBox="0 0 48 48" aria-hidden="true"><path d="M7 8h34v32H7zM13 14l22 20M35 14L13 34M7 24h34M24 8v32"/><circle cx="24" cy="24" r="7"/></svg>}
function MiniWave({seed=0}:{seed?:number}){return <svg className="mini-wave" viewBox="0 0 100 30" preserveAspectRatio="none"><polyline points={Array.from({length:12},(_,i)=>`${i*9},${15+Math.sin(i*1.7+seed)*8+(i%3)*2}`).join(' ')}/></svg>}
function BlueprintSkeleton(){return <div className="blueprint"><div className="scan"/><header><i/><b/><span/></header><aside><b/><i/><i/><i/></aside><section><header/><div className="sk-hero"><i/><b/></div><div className="sk-events"><i/><i/><i/><i/></div></section><article><b/><div/><div/><div/></article><footer/></div>}

export default function Home(){
 const[loading,setLoading]=useState(true),[active,setActive]=useState('INC-2471'),[modal,setModal]=useState(false),[panel,setPanel]=useState<'matrix'|'protocol'>('matrix'),[clock,setClock]=useState(''),[wallet,setWallet]=useState(''),[phase,setPhase]=useState(''),[hash,setHash]=useState(''),[error,setError]=useState(''),[chainItems,setChainItems]=useState<any[]>([]),[assessment,setAssessment]=useState<any>(),[form,setForm]=useState({title:'',service:'',symptoms:'',action:'',risk:'',recovery:''});
 const refresh=async()=>{try{const p:any=await read('get_incidents_page',[0,50]);const items=p.items||[];setChainItems(items);if(items.length&&!items.some((x:any)=>x.id===active)){const assessed=[...items].reverse().find((x:any)=>x.status==='assessed');setActive((assessed||items[items.length-1]).id)}}catch{}};
 useEffect(()=>{const t=setTimeout(()=>setLoading(false),950);const tick=setInterval(()=>setClock(new Date().toLocaleTimeString('en-GB',{hour12:false})),1000);refresh();return()=>{clearTimeout(t);clearInterval(tick)}},[]);
 const live:Incident[]=chainItems.map(x=>({id:x.id,title:x.title,service:x.service,severity:x.severity,elapsed:'ON-CHAIN',status:String(x.status).toUpperCase(),signal:x.severity==='SEV-1'?91:x.severity==='SEV-2'?68:40}));const shown=live.length?live:incidents;
 const incident=useMemo(()=>shown.find(x=>x.id===active)||shown[0],[active,chainItems]);
 useEffect(()=>{setAssessment(undefined);if(incident?.status==='ASSESSED')read('get_assessment',[incident.id]).then(setAssessment).catch(()=>{})},[incident?.id,incident?.status]);
 const progress=(p:string,h?:string)=>{setPhase(p);if(h)setHash(h)};
 const busy=['WALLET APPROVAL','AI CONSENSUS','RECONNECTING TO BRADBURY'].includes(phase);
 const openIncident=async()=>{try{setError('');const id=`INC-${crypto.randomUUID().slice(0,8).toUpperCase()}`;await write('open_incident',[id,form.title,form.service,'SEV-2',form.symptoms,[form.action],[form.risk],form.recovery],progress);setModal(false);setActive(id);await refresh()}catch(e:any){setError(String(e?.message||e));setPhase('FAILED')}};
 const assess=async()=>{try{setError('');await write('assess_incident',[incident.id],progress);setAssessment(await read('get_assessment',[incident.id]));await refresh()}catch(e:any){setError(String(e?.message||e));setPhase('FAILED')}};
 if(loading)return <main><BlueprintSkeleton/></main>;
 return <main className="shell">
  <div className="noise"/><div className="beam"/>
  <header className="topbar"><div className="brand"><LoomMark/><div><b>INCIDENT<span>LOOM</span></b><small>CONSENSUS COMMAND FABRIC</small></div></div><div className="system"><span><i/> STUDIONET ON-CHAIN</span><span>UTC {clock}</span><span>SHIFT / ALPHA-04</span></div><button className="identity" disabled={busy} onClick={async()=>{try{setWallet(await connect())}catch(e:any){setError(String(e?.message||e))}}}>{wallet?`${wallet.slice(0,6)}...${wallet.slice(-4)}`:'CONNECT WALLET'}</button></header>
  <nav className="command-tabs"><button className="active">COMMAND WALL</button><button>ARCHIVE</button><button>PROTOCOLS</button><span>{shown.length.toString().padStart(2,'0')} INCIDENTS</span></nav>
  <div className="workspace">
   <aside className="incident-stack"><div className="section-head"><span>01</span><b>INCIDENT FEED</b><button onClick={()=>setModal(true)}>OPEN +</button></div><div className="stack">{shown.map((x,i)=><motion.button key={x.id} className={active===x.id?'selected':''} onClick={()=>setActive(x.id)} initial={{x:-22,opacity:0}} animate={{x:0,opacity:1}} transition={{delay:i*.08}}><div className="incident-code"><span>{x.id}</span><b data-sev={x.severity}>{x.severity}</b></div><h3>{x.title}</h3><small>{x.service}</small><MiniWave seed={i}/><div className="incident-meta"><span>{x.elapsed}</span><span>{x.status}</span><span>{x.signal}%</span></div></motion.button>)}</div><div className="feed-foot"><span>INGRESS HEALTH</span><b>99.94%</b><i/></div></aside>
   <section className="timeline"><div className="incident-hero"><div><span className="eyebrow">{incident.id} / {incident.service}</span><h1>{incident.title}</h1><p>Revocation commands are accepted but propagation is delayed across regional session caches.</p></div><div className="severity-orbit"><div><b>{incident.severity}</b><span>COUNCIL</span></div><i/><i/><i/></div></div>
    <div className="timeline-toolbar"><span>02 / SITUATION SPINE</span><div><button>ALL SIGNALS</button><button>REPORTS</button><button>ACTIONS</button></div><b>LIVE</b></div>
    <div className="event-spine">{events.map((e,i)=><motion.article key={e.time} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.15+i*.1}}><div className="time">{e.time}<i/></div><div className="event"><span data-kind={e.kind}>{e.kind}</span><h2>{e.title}</h2><p>{e.body}</p><small>{e.author}</small></div></motion.article>)}</div>
    <button className="situation-button" onClick={()=>setModal(true)}><span>+</span> ADD SITUATION REPORT <i>SEAL NEW EVIDENCE INTO THE INCIDENT</i></button>
   </section>
   <aside className="containment"><div className="panel-switch"><button className={panel==='matrix'?'active':''} onClick={()=>setPanel('matrix')}>MATRIX</button><button className={panel==='protocol'?'active':''} onClick={()=>setPanel('protocol')}>PROTOCOL</button></div>{panel==='matrix'?<><div className="section-head compact"><span>03</span><b>BLAST MATRIX</b></div><div className="matrix"><div/><span>USER IMPACT</span><span>DATA RISK</span><span>SPREAD</span><b>IDENTITY</b><i className="hot">91</i><i>12</i><i className="hot">84</i><b>SESSION</b><i className="warm">73</i><i>08</i><i className="warm">61</i><b>AUDIT</b><i>22</i><i>04</i><i>19</i></div><div className="domain"><span>LIKELY FAILURE DOMAIN</span><b>CACHE INVALIDATION BUS</b><small>Confidence band / 82–91%</small><MiniWave seed={4}/></div><div className="rail"><span>CONTAINMENT ORDER</span>{['Protect revocation writes','Drain stale cache queue','Replay forensic stream'].map((x,i)=><div key={x}><i>{i+1}</i><b>{x}</b><span className={i===0?'done':''}>{i===0?'ACTIVE':'QUEUED'}</span></div>)}</div></>:<div className="protocol"><span>ACTIVE PLAYBOOK</span><h3>Identity propagation / P-17</h3>{['Confirm multi-region impact','Preserve queue evidence','Isolate priority writes','Measure cache convergence','Authorize recovery'].map((x,i)=><div key={x} className={i<2?'done':''}><i>{i<2?'✓':i+1}</i><span>{x}</span></div>)}</div>}
    {assessment&&<motion.div className="assessment-result" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><header><span>VALIDATOR VERDICT</span><b>{assessment.outcome}</b></header><div><span>RISK / {assessment.risk}</span><strong>{assessment.confidence}% CONFIDENCE</strong></div><p>{assessment.summary}</p><small>REQUIRED NEXT ACTIONS</small>{(assessment.requiredActions||[]).map((x:string,i:number)=><label key={x}><i>{i+1}</i>{x}</label>)}</motion.div>}
    <button className="council-button" onClick={assess} disabled={!wallet||busy||incident.status==='ASSESSED'}><span>{incident.status==='ASSESSED'?'ASSESSMENT COMPLETE':phase||'REQUEST COUNCIL'}</span><b>{assessment?assessment.outcome:'ASSESS NEXT CONTAINMENT GATE'}</b><LoomMark/></button>
   </aside>
  </div>
  <footer><span>GENLAYER / INDEPENDENT AI VALIDATORS</span><div><i/><i/><i/><i/><i/></div><b>FABRIC STABLE · 5 NODES READY</b></footer>
  <AnimatePresence>{modal&&<><motion.div className="scrim" onClick={()=>setModal(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.section className="report-modal" initial={{scale:.94,y:22,opacity:0}} animate={{scale:1,y:0,opacity:1}} exit={{scale:.96,y:18,opacity:0}}><div className="modal-head"><span>NEW ON-CHAIN INCIDENT</span><button onClick={()=>setModal(false)}>CLOSE ×</button></div><h2>Seal operational evidence</h2><p>The incident becomes immutable on StudioNet. Add a detailed observation of at least 24 characters.</p><label>SIGNAL TITLE<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Revocation latency crossed 30s"/></label><div className="form-row"><label>SERVICE<input value={form.service} onChange={e=>setForm({...form,service:e.target.value})} placeholder="IDENTITY EDGE"/></label><label>KNOWN RISK<input value={form.risk} onChange={e=>setForm({...form,risk:e.target.value})} placeholder="stale sessions"/></label></div><label>OBSERVATION<textarea value={form.symptoms} onChange={e=>setForm({...form,symptoms:e.target.value})} placeholder="What is directly observable? Include scope and timing."/></label><label>ACTION / RECOVERY<input value={form.action} onChange={e=>setForm({...form,action:e.target.value,recovery:e.target.value})} placeholder="Isolate priority writes and preserve the queue"/></label><button className="seal" disabled={!wallet||busy||form.title.length<3||form.symptoms.length<24} onClick={openIncident}>{phase||'SEAL INTO INCIDENT'} <LoomMark/></button></motion.section></>}</AnimatePresence>
  {(phase||error)&&<div className={`chain-progress ${error?'failed':''}`}><b>{error?'TRANSACTION NEEDS ATTENTION':phase}</b><span>{error||'Keep this page open while GenLayer validators agree.'}</span>{hash&&<a href={`${EXPLORER}/${hash}`} target="_blank">VIEW TRANSACTION ↗</a>}<button onClick={()=>{setPhase('');setError('')}}>×</button></div>}
 </main>
}
